import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>zzZ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a >zzZ!</a>
        </h1>
        <div className={styles.grid}>
          
          <a href="./events" className={styles.card}>
            <h2>Events &rarr;</h2>
            <p>Find in-depth information about zzZ features and upcoming events</p>
          </a>
          

</div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
    
  )
}

export default Home
